name: auth3_login
version: 1.0.1
homepage: https://auth3.dev
repository: https://github.com/auth3-dev/dart-sdk
description: Official Auth3 Login SDK for Flutter, read more at https://auth3.dev/.
documentation: https://docs.auth3.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

