name: auth3_login
version: 1.2.2
homepage: https://auth3.dev
repository: https://github.com/auth3-dev/dart-sdk
description: Official Auth3 Login SDK for Flutter, read more at https://auth3.dev/.
documentation: https://docs.auth3.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.4.1
  flutter_secure_storage: ^5.0.2
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
