name: auth3_admin_sdk
version: 1.0.0
homepage: https://auth3.dev
repository: https://github.com/auth3-dev/dart-sdk
description: Official Auth3 Identity Platform Admin SDK, read more at https://auth3.dev/.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  grpc: ^2.1.3
  protobuf: ^1.0.1
  fixnum: ^0.10.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
